version: "3"
services:
  db:
    image: ealgis/postgis:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PG_PASSWORD=postgres
      - DB_NAME=perth
    volumes:
      - .:/data
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
