version: "3"
services:
  db:
    image: ealgis/postgis:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=perth
    volumes:
      - .:/data
      - pgdata:/var/lib/postgresql/data
  labyrinth:
    build:
      context: labyrinth/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - DB_PASSWORD=postgres
      - DB_NAME=perth
      - DB_HOST=db
    depends_on:
    - db
volumes:
  pgdata:
